# Generated by Django 4.0.3 on 2022-03-18 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0003_alter_question_options'),
        ('notifications', '0003_notification_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='contentA',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='contentQ',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='contentType',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='link',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='receiver',
        ),
        migrations.AddField(
            model_name='notification',
            name='receivers',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.question'),
        ),
    ]
