# Generated by Django 4.0.3 on 2022-03-19 07:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0005_alter_notification_receivers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='receivers',
            field=models.ManyToManyField(blank=True, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
