# Generated by Django 4.0.3 on 2022-03-21 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_question_title'),
        ('notifications', '0006_alter_notification_receivers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='target_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.question'),
        ),
    ]
