# Generated by Django 4.0.3 on 2022-04-28 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_alter_notification_target_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['timestamp']},
        ),
    ]
