# Generated by Django 4.0.3 on 2022-04-28 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_alter_notification_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-timestamp']},
        ),
    ]
