# Generated by Django 4.0.3 on 2022-04-05 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Question_for_polls',
        ),
    ]
