# Generated by Django 4.0.3 on 2022-03-09 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('answers', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.content')),
                ('parentObjType', models.CharField(max_length=200)),
                ('parentObjA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.answer')),
            ],
            bases=('home.content',),
        ),
    ]
