# Generated by Django 4.0.3 on 2022-03-14 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_initial'),
        ('questions', '0006_delete_question2'),
        ('comments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parentObjA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='answers.answer'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parentObjQ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.question'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parentObjType',
            field=models.CharField(choices=[('q', 'Question'), ('a', 'Answer')], max_length=1),
        ),
    ]
