# Generated by Django 4.0.3 on 2022-03-11 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_initial'),
        ('questions', '0003_auto_20220310_0515'),
        ('comments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parentObjA',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='answers.answer'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parentObjQ',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='questions.question'),
        ),
    ]
