# Generated by Django 3.2.12 on 2022-03-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_alter_comment_parentobja_alter_comment_parentobjq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parentObjType',
            field=models.CharField(choices=[('q', 'Question'), ('a', 'Answer')], max_length=1),
        ),
    ]
