# Generated by Django 3.2.12 on 2022-03-14 10:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='viewedBy',
            field=models.ManyToManyField(blank=True, related_name='viewedBy', to=settings.AUTH_USER_MODEL),
        ),
    ]
