# Generated by Django 4.0.3 on 2022-03-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('questions', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(related_name='relatedto', to='tags.tag'),
        ),
        migrations.AddField(
            model_name='question',
            name='viewedBy',
            field=models.ManyToManyField(related_name='viewedBy', to='users.user'),
        ),
    ]
