# Generated by Django 3.2.12 on 2022-03-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_initial'),
        ('users', '0001_initial'),
        ('questions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='relatedto', to='tags.Tag'),
        ),
        migrations.AlterField(
            model_name='question',
            name='viewedBy',
            field=models.ManyToManyField(blank=True, related_name='viewedBy', to='users.User'),
        ),
    ]
