# Generated by Django 3.2.12 on 2022-03-13 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20220310_0515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='numViews',
        ),
    ]
