# Generated by Django 4.0.3 on 2022-04-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('questions', '0004_alter_question_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(to='tags.tag'),
        ),
    ]
