# Generated by Django 4.0.3 on 2022-03-14 05:56

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_content_pub_date_alter_content2_pub_date'),
        ('tags', '0004_remove_tag_users_lst'),
        ('users', '0014_auto_20220313_1252'),
        ('questions', '0004_remove_question_numviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question2',
            fields=[
                ('content2_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.content2')),
                ('text', ckeditor.fields.RichTextField()),
                ('title', models.CharField(max_length=200)),
                ('tags', models.ManyToManyField(blank=True, related_name='relatedto2', to='tags.tag')),
                ('viewedBy', models.ManyToManyField(blank=True, related_name='viewedBy2', to='users.user')),
            ],
            bases=('home.content2',),
        ),
    ]
