# Generated by Django 4.0.3 on 2022-03-14 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_question2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question2',
        ),
    ]
