# Generated by Django 3.2.12 on 2022-03-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20220310_0515'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bookmarkQuestions',
            field=models.ManyToManyField(blank=True, related_name='user_bq', to='questions.Question'),
        ),
        migrations.AlterField(
            model_name='user',
            name='followingQuestions',
            field=models.ManyToManyField(blank=True, related_name='user_fq', to='questions.Question'),
        ),
    ]
