# Generated by Django 4.0.3 on 2022-03-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_viewedby'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bookmarkQuestions',
            field=models.ManyToManyField(blank=True, related_name='users_bookmarked', to='questions.question'),
        ),
        migrations.AlterField(
            model_name='user',
            name='followingQuestions',
            field=models.ManyToManyField(blank=True, related_name='users_following', to='questions.question'),
        ),
    ]
