# Generated by Django 4.0.3 on 2022-03-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220310_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roll_no',
            field=models.IntegerField(default=0, max_length=8),
        ),
    ]
