# Generated by Django 4.0.3 on 2022-03-14 17:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_bookmarkquestions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reported_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='reportedObjType',
            field=models.CharField(choices=[('q', 'Question'), ('a', 'Answer'), ('c', 'Comment')], max_length=1),
        ),
    ]
