# Generated by Django 4.0.3 on 2022-03-15 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_report_reported_on_alter_report_reportedobjtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='report_date',
        ),
    ]
