# Generated by Django 4.0.3 on 2022-03-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roll_no',
            field=models.IntegerField(default=0),
        ),
    ]
