# Generated by Django 4.0.3 on 2022-03-25 10:31

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, validators=[users.models.EmailValidator()], verbose_name='email address'),
        ),
    ]
