# Generated by Django 3.2.12 on 2022-03-13 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_favouritetags'),
        ('users', '0012_alter_user_last_login'),
    ]

    operations = [
    ]
