# Generated by Django 3.2.12 on 2022-03-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_remove_tag_users_lst'),
        ('users', '0013_merge_20220313_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verified',
        ),
        migrations.AddField(
            model_name='user',
            name='favouriteTags',
            field=models.ManyToManyField(blank=True, to='tags.Tag'),
        ),
    ]
