# Generated by Django 3.2.12 on 2022-03-12 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_alter_tag_users_lst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='users_lst',
        ),
    ]
