# Generated by Django 4.0.3 on 2022-03-14 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_answer_parentobj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='parentObj',
            new_name='to_question',
        ),
    ]
