# Generated by Django 3.2.12 on 2022-03-14 10:58

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField()),
                ('anonymous', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2022, 3, 14, 16, 28, 52, 308484), verbose_name='date published')),
            ],
        ),
    ]
