# Generated by Django 4.0.3 on 2022-03-14 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 14, 18, 49, 53, 573526), verbose_name='date published'),
        ),
    ]
