# Generated by Django 4.0.3 on 2022-03-13 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_content_pub_date'),
        ('home', '0007_auto_20220313_1551'),
    ]

    operations = [
    ]
