# Generated by Django 4.0.3 on 2022-03-13 20:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_merge_20220314_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 14, 2, 0, 24, 577275), verbose_name='date published'),
        ),
    ]
