# Generated by Django 3.2.12 on 2022-03-15 04:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_content_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 15, 9, 49, 39, 7279), verbose_name='date published'),
        ),
    ]
