# Generated by Django 4.0.3 on 2022-03-14 05:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20220313_1252'),
        ('home', '0010_alter_content_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 14, 11, 24, 18, 636530), verbose_name='date published'),
        ),
        migrations.CreateModel(
            name='Content2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2022, 3, 14, 11, 24, 18, 656619), verbose_name='date published')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author2', to='users.user')),
                ('dislikedBy', models.ManyToManyField(blank=True, related_name='dislikedBy2', to='users.user')),
                ('likedBy', models.ManyToManyField(blank=True, related_name='likedBy2', to='users.user')),
            ],
        ),
    ]
