# Generated by Django 4.0.3 on 2022-03-14 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_content_pub_date_content2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 14, 11, 26, 5, 560806), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='content2',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 14, 11, 26, 5, 581665), verbose_name='date published'),
        ),
    ]
