# Generated by Django 4.0.3 on 2022-03-14 06:07

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_delete_question2'),
        ('home', '0012_alter_content_pub_date_alter_content2_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 14, 11, 37, 5, 314975), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='content',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.DeleteModel(
            name='Content2',
        ),
    ]
