# Generated by Django 3.2.12 on 2022-03-15 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_content_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 16, 2, 55, 13, 918109), verbose_name='date published'),
        ),
    ]
