# Generated by Django 4.0.3 on 2022-03-14 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_content_pub_date_content_for_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 14, 11, 47, 35, 593609), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='content_for_comments',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 14, 11, 47, 35, 613845), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='content_for_comments',
            name='text',
            field=models.CharField(default='hii', max_length=1000),
        ),
    ]
