# Generated by Django 4.0.3 on 2022-03-14 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_content_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 14, 11, 48, 4, 284318), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='content_for_comments',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 14, 11, 48, 4, 304961), verbose_name='date published'),
        ),
    ]
