# Generated by Django 4.0.3 on 2022-03-17 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_content_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 17, 18, 40, 10, 442269), verbose_name='date published'),
        ),
    ]
