# Generated by Django 4.0.3 on 2022-03-25 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_content_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 25, 22, 28, 1, 864801), verbose_name='date published'),
        ),
    ]
