# Generated by Django 3.2.12 on 2022-04-03 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_content_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 3, 13, 4, 30, 216925), verbose_name='date published'),
        ),
    ]
