<<<<<<< HEAD
# Generated by Django 4.0.3 on 2022-04-19 14:34
=======
# Generated by Django 4.0.3 on 2022-04-19 22:02
>>>>>>> babe3f42b81f30e8bfb568267268b7957f075ad6

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_alter_content_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='pub_date',
<<<<<<< HEAD
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 19, 20, 4, 53, 996941), null=True, verbose_name='date published'),
=======
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 20, 3, 32, 12, 196508), null=True, verbose_name='date published'),
>>>>>>> babe3f42b81f30e8bfb568267268b7957f075ad6
        ),
    ]
