# Generated by Django 4.0.3 on 2022-04-19 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_alter_content_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 19, 20, 4, 53, 996941), null=True, verbose_name='date published'),
        ),
    ]
