# Generated by Django 4.0.3 on 2022-04-28 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_alter_content_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 28, 21, 50, 32, 425473), null=True, verbose_name='date published'),
        ),
    ]
